// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeWMServiceServer is an autogenerated mock type for the UnsafeWMServiceServer type
type UnsafeWMServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedWMServiceServer provides a mock function with given fields:
func (_m *UnsafeWMServiceServer) mustEmbedUnimplementedWMServiceServer() {
	_m.Called()
}

// NewUnsafeWMServiceServer creates a new instance of UnsafeWMServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeWMServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeWMServiceServer {
	mock := &UnsafeWMServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
